### GET request to example server
GET http://localhost:8080/api/v1/books
###
GET http://localhost:8080/api/v1/books/1
###
GET http://localhost:8080/api/v1/books/search?title=9 лет я сосал залупы&author=Даун ебаный
###
POST http://localhost:8080/api/v1/books
Content-Type: application/json

{
  "title": "ывфвфыв",
  "author": "ывфывыфв",
  "isbn": "ISBN 978-5-43789-231-2",
  "publicationYear":1984,
  "totalCopies": 88,
  "availableCopies":6
}

###
PUT http://localhost:8080/api/v1/books/1
Content-Type: application/json

{
  "title": "sdasd",
  "author": "dsada",
  "isbn": "ISBN 978-5-43789-231-2",
  "publicationYear":2012,
  "totalCopies": 88,
  "availableCopies":6
}
###
POST http://localhost:8080/api/v1/readers
Content-Type: application/json

{
  "firstName": "hjgj",
  "lastName": "hjkhjk",
  "email": "sda@mail.ru",
  "phone": "12312412"
}
###
GET http://localhost:8080/api/v1/readers/1
###
POST http://localhost:8080/api/v1/loans
Content-Type: application/json

{
  "bookId":1 ,
  "readerId": 1,
  "dueDate": "2026-10-15"

}
###
GET http://localhost:8080/api/v1/loans/get
###
PUT http://localhost:8080/api/v1/loans/return/1
###
PUT http://localhost:8080/api/v1/loans/overdue/2
###
GET http://localhost:8080/api/v1/loans/reader/1
###
GET http://localhost:8080/api/v1/loans/overdue
###
GET http://localhost:8080/api/v1/loans/overdue/list
###
GET http://localhost:8080/api/v1/books/search/-1984
###
GET http://localhost:8080/api/v1/books/retryable-operation?param1=param1&param2=param2
###
GET http://localhost:8080/actuator/heapdump